### PR TITLE
(doc) Add "Table of Contents" in ReadMe.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This helps quickly find the content we need ;)

### CODE REVIEW

**Comment by ferventcoder** [comment]
@PeterDaveHello thanks for this - hopefully you used a tool like Alan Walk's Markdown TOC - https://github.com/AlanWalk/Markdown-TOC#3-usage.

**Comment by ferventcoder** [comment]
I'd pull it in, but it doesn't appear I have the good permissions yet - paging @gep13

**Comment by PeterDaveHello** [comment]
Oh, I use vim, but maybe we can integrate preferred tool with CI if it's needed ;)

**Comment by gep13** [comment]
@PeterDaveHello your changes have been merged, thanks for your contribution 👍

**Pull request merged**
